### ISSUE TITLE
images within a public page

### ISSUE THREAD

**Issue by avelino** [logseq/publish-spa#6] opened 2023-05-11 12:13 UTC
if you place an image inside a public page, that image is not populated (in the output folder)

e.g: http://notes.avelino.run/#/page/livro%2Fmarketing%205.0

**Comment by logseq-cldwalker** [comment] 2023-05-11 21:19
Hi. This sounds like a duplicate of https://github.com/logseq/logseq/issues/7150. If it's not, would recommend opening an issue on the logseq repo with reproducible steps. This repo is for behavior on the github action or CLI. I've updated the issue template on this repo to make it clear going forward

**Closed** 2023-05-11 21:41 UTC
