### ISSUE TITLE
[feature request] generate multiple html files instead of a (potentially) huge one

### ISSUE THREAD

**Issue by emacsbliss** [logseq/publish-spa#25] opened 2024-02-11 22:44 UTC
### What Happened?

publish-spa will only generate one html (`index.html`) which contains all the pages for a given graph.

This approach works reasonably well for small graph but it does not scale well for large graph. 

For example with my graph (contains about 5000 files), it produces a index.html with 77M size which is not practical to serve it for a web server..

### Reproduce the Bug

I just run `logseq-publish-spa out` under my graph root directory

### Expected Behavior

generate multiple html files (maybe one per page?) instead of only index.html

### Desktop or Mobile Platform Information

MacOS: 14.2 (23C64)
Logseq App: Version 0.10.6 (80)
latest version of logseq-publish-spa

**Comment by logseq-cldwalker** [comment] 2024-02-12 14:35
Hi. Closing as this is a duplicate of https://github.com/logseq/publish-spa/issues/13. That issue has relevant links that could be helpful

**Closed by logseq-cldwalker** 2024-02-12 14:35 UTC
Labels: duplicate
